#!/bin/bash
# After synthetic reads are generated by ART Illumina, run the Bowtie2 for read mapping

mtb_genome="./mtb-genome-extract.fna"

# Build index for MTB reference genome
bowtie2-build $mtb_genome mtb

# Single mapping, best-match for MTB
bowtie2 -x mtb -U mtb-single-end.fq -S mtb-single-end-mapping-best-match.sam 2> log-mtb-single-end-mapping-best-match.txt

# Single mapping, report-all for MTB
bowtie2 -a -x mtb -U mtb-single-end.fq -S mtb-single-end-mapping-report-all.sam 2> log-mtb-single-end-mapping-report-all.txt


echo "\n=== Done ===\n"
